import { useState } from "react";
import { FileDown, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface BriefPdfExportProps {
  candidateName: string;
  position: string;
  brief: {
    synthesis: {
      summary: string;
      strengths: string[];
      risks: string[];
      customQuestions: { question: string; rationale: string; targetGap: string }[];
      confidenceScore: number;
      recommendation: "advance" | "review" | "reject";
    };
    webPresence?: {
      linkedinSummary?: string;
      githubSummary?: string;
      rawSkills?: string[];
      experience?: string;
    } | null;
    sources?: string[];
    pipelineDurationMs?: number;
  };
}

function buildPrintHtml(props: BriefPdfExportProps): string {
  const { candidateName, position, brief } = props;
  const { synthesis } = brief;

  const recColor =
    synthesis.recommendation === "advance"
      ? "#16a34a"
      : synthesis.recommendation === "reject"
        ? "#dc2626"
        : "#d97706";

  const recLabel =
    synthesis.recommendation.charAt(0).toUpperCase() + synthesis.recommendation.slice(1);

  const strengthsHtml = synthesis.strengths
    .map((s) => `<li>${s}</li>`)
    .join("");

  const risksHtml = synthesis.risks
    .map((r) => `<li>${r}</li>`)
    .join("");

  const questionsHtml = synthesis.customQuestions
    .map(
      (q) => `
      <div style="margin-bottom:12px;padding:10px;background:#f9fafb;border-radius:6px;border:1px solid #e5e7eb;">
        <p style="margin:0 0 4px;font-weight:600;font-size:14px;">${q.question}</p>
        <p style="margin:0 0 4px;font-size:12px;color:#6b7280;font-style:italic;">${q.rationale}</p>
        <span style="display:inline-block;padding:2px 8px;background:#e0e7ff;color:#3730a3;border-radius:4px;font-size:11px;">${q.targetGap}</span>
      </div>`
    )
    .join("");

  const webPresenceHtml = brief.webPresence
    ? `
    <h2 style="font-size:16px;margin:24px 0 8px;color:#111;">Web Presence</h2>
    ${brief.webPresence.rawSkills?.length ? `<p style="font-size:13px;"><strong>Skills:</strong> ${brief.webPresence.rawSkills.join(", ")}</p>` : ""}
    ${brief.webPresence.experience ? `<p style="font-size:13px;"><strong>Experience:</strong> ${brief.webPresence.experience}</p>` : ""}
    ${brief.webPresence.linkedinSummary ? `<p style="font-size:13px;"><strong>LinkedIn:</strong> ${brief.webPresence.linkedinSummary.slice(0, 500)}</p>` : ""}
    ${brief.webPresence.githubSummary ? `<p style="font-size:13px;"><strong>GitHub:</strong> ${brief.webPresence.githubSummary.slice(0, 500)}</p>` : ""}
    `
    : "";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Intelligence Brief - ${candidateName}</title>
  <style>
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
    body { font-family: Georgia, "Times New Roman", serif; max-width: 700px; margin: 40px auto; padding: 0 24px; color: #111; line-height: 1.6; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 20px; }
    .rec-badge { display: inline-block; padding: 4px 14px; border-radius: 6px; font-weight: 700; font-size: 14px; color: white; }
    .meta-row { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; }
    .confidence { font-size: 14px; color: #6b7280; }
    .confidence strong { font-size: 20px; color: #111; }
    h2 { font-size: 16px; margin: 24px 0 8px; color: #111; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 6px; font-size: 14px; }
    .strengths li::marker { color: #16a34a; }
    .risks li::marker { color: #dc2626; }
    .summary { font-size: 14px; color: #374151; white-space: pre-line; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
  </style>
</head>
<body>
  <h1>${candidateName}</h1>
  <p class="subtitle">${position}</p>

  <div class="meta-row">
    <span class="rec-badge" style="background:${recColor};">${recLabel}</span>
    <span class="confidence"><strong>${synthesis.confidenceScore}</strong>/100 confidence</span>
  </div>

  <h2>Summary</h2>
  <p class="summary">${synthesis.summary}</p>

  ${strengthsHtml ? `<h2>Strengths</h2><ul class="strengths">${strengthsHtml}</ul>` : ""}
  ${risksHtml ? `<h2>Risks</h2><ul class="risks">${risksHtml}</ul>` : ""}
  ${questionsHtml ? `<h2>Suggested Interview Questions</h2>${questionsHtml}` : ""}
  ${webPresenceHtml}

  <div class="footer">
    Generated by TrueVoice Joan AI &middot; ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body>
</html>`;
}

export function BriefPdfExport({ candidateName, position, brief }: BriefPdfExportProps) {
  const [loading, setLoading] = useState(false);

  const handleExport = () => {
    setLoading(true);
    try {
      const html = buildPrintHtml({ candidateName, position, brief });
      const printWindow = window.open("", "_blank");
      if (!printWindow) {
        setLoading(false);
        return;
      }
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
        setLoading(false);
      };
      setTimeout(() => setLoading(false), 3000);
    } catch {
      setLoading(false);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleExport}
      disabled={loading}
      className="gap-1.5"
    >
      {loading ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
      ) : (
        <FileDown className="h-3.5 w-3.5" />
      )}
      Export PDF
    </Button>
  );
}
